apps/home/urls.py
from django.conf.urls import url
from views import *
urlpatterns = [
    url(r'^$', index, name='home'),
    url(r'^add/item/$', add_item, name='add'),
    url(r'^wish/(?P<wish_id>\d+)$', add_wish, name='wish'),
    url(r'^unwish/(?P<wish_id>\d+)$', remove_wish, name='unwish'),
    url(r'^item/(?P<item_id>\d+)$', item, name='item'),
    url(r'^delete(?P<item_id>\d+)$', delete, name='delete')
]

apps/main/urls.py
from django.conf.urls import url
from views import *
urlpatterns = [
    url(r'^$', index, name='home'),
    url(r'^register$', register, name='register'),
    url(r'^login$', login, name='login'),
    url(r'^logout$', logout, name='logout')
]

belt2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.main.urls', namespace='user')),
    url(r'^dashboard/', include('apps.home.urls', namespace='home'))
]

apps/home/models.py
from __future__ import unicode_literals
from django.db import models
from ..main.models import User

class Item(models.Model):
    title=models.CharField(max_length=64)
    user=models.ForeignKey(User, related_name='items')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

class Wish(models.Model):
    wish=models.ForeignKey(Item, related_name='wishers')
    wisher=models.ForeignKey(User, related_name='wishes')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

apps/main/models.py
from __future__ import unicode_literals

from django.db import models

class User(models.Model):
    name=models.CharField(max_length=64)
    user_name=models.CharField(max_length=64)
    email=models.EmailField(unique=True)
    password=models.CharField(max_length=64)
    hired=models.DateField()
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

apps/home/views.py
from django.shortcuts import render, redirect
from .models import Item, Wish
from ..main.models import User
from django.contrib import messages

def index(request):
    if 'user_id' in request.session:
        user=request.session['user_id']
        context={
            'items': Item.objects.exclude(wishers__wisher_id=user),
            'wishes': Wish.objects.filter(wisher_id=user),
            'all': Wish.objects.all()
        }
    return render(request,'home/index.html', context)

def add_item(request):
    if request.method == 'POST':
        wish=request.POST['wish_name']
        if len(wish)>3:
            items=Item.objects.create(title=wish, user_id=request.session['user_id'])
            Wish.objects.create(wish_id=items.id, wisher_id=request.session['user_id'])
            return redirect('home:home')
        else:
             messages.add_message(request,messages.ERROR,'Item must be at least 3 characters')
             return redirect('home:add')
            

    return render(request,'home/add.html')

def add_wish(request, wish_id):
    Wish.objects.create(wish_id=wish_id, wisher_id=request.session['user_id'])
    return redirect('home:home')
def remove_wish(request, wish_id):
    Wish.objects.get(wish_id=wish_id, wisher_id=request.session['user_id']).delete()
    return redirect('home:home')

def item(request, item_id):
    context={
        'item': Item.objects.get(id=item_id),
        'wish': Wish.objects.filter(wish_id=item_id)
    }
    return render(request, 'home/item.html', context)

def delete(request, item_id):
    Item.objects.get(id=item_id, user_id=request.session['user_id']).delete()
    return redirect('home:home')

apps/main/views.py
from django.shortcuts import render, redirect,reverse
from django.contrib import messages
import bcrypt
import re
from .models import User
import datetime

REGEX=re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

def index(request):
    return render(request,'main/index.html')

def register(request):
    name=request.POST['html_name']
    email=request.POST['html_email']
    username=request.POST['html_username']
    password=request.POST['html_password']
    password_confirm=request.POST['html_confirm']
    date=request.POST['html_date']
    auth=True
    if len(name)<2:
        auth=False
        messages.add_message(request,messages.ERROR,'Name must be at least 3 characters')
    if len(username)<2:
        auth=False
        messages.add_message(request,messages.ERROR,'Username must be at least 3 characters')
    if not REGEX.match(email):
        auth=False
        messages.add_message(request,messages.ERROR,'Invalid Email')
    if len(password)<8:
        auth=False
        messages.add_message(request,messages.ERROR,'Passwords must be at least 8 characters long')
    if password!=password_confirm:
        auth=False
        messages.add_message(request,messages.ERROR,'Passwords do not match')
    
    if auth == True:
        try:
            hashed_password=bcrypt.hashpw(password.encode('UTF-8'),bcrypt.gensalt())    
            user = User.objects.create(name=name, email=email, password=hashed_password, user_name=username, hired=date)
            request.session['user_id']=user.id
            request.session['user_name']=user.user_name
            return redirect('home:home')
        except:
             messages.add_message(request,messages.ERROR,'Email already exists')
             return redirect('user:home')

    else:
        return redirect('user:home')

def login(request):
    username=request.POST['html_username']
    server_password=request.POST['html_password']

    try:
        user = User.objects.get(user_name=username)
        if user.password == bcrypt.hashpw(server_password.encode('UTF-8'), user.password.encode('UTF-8')):

            request.session['user_id'] = user.id
            request.session['user_name'] = user.name
            return redirect('home:home')
        else:
            messages.add_message(request,messages.ERROR,'Invalid login')
            return redirect('user:home')
                      
    except:
        messages.add_message(request,messages.ERROR,'Username does not exist')
        return redirect('user:home')

def logout(request):
    request.session.clear()
    return redirect('user:home')

apps/home/templates/home/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <title>Create Item</title>
    
</head>
<body>
    <p><a href="{% url 'user:logout' %}">Logout</a> <a href="{% url 'home:home' %}">Home</a></p>
    <h1>Create A New Wish List Item</h1>
    <form action="{% url 'home:add' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="wish_name">
    <input type="submit" value="Add">

    </form>
    {% for m in messages %}
        {{m}}
    {% endfor %}
</body>
</html>

apps/home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
   
    <title>{{request.session.user_name}}</title>
    
</head>
<body>
    <p><a href="{% url 'user:logout' %}">Logout</a></p>
    <h1>Hello {{request.session.user_name}}!</h1>
    <h2>Your Wish List</h2>

    {% for wish in wishes %}

        <h3><a href="{% url 'home:item' item_id=wish.wish.id %}">
        {{wish.wish.title}}</a>

         By: {{wish.wish.user.name}} added on {{wish.created_at}} 
         {% if request.session.user_id == wish.wish.user.id %}
         <a href="{% url 'home:delete' item_id=wish.wish_id %}"> Delete </a>
         {% else %}
         <a href="{% url 'home:unwish' wish_id=wish.wish_id %}"> Remove from my Wish List </a>
         {% endif %}
         
    {% endfor %}
    </h3>
    <hr><hr>
    <h2>Others Wish Lists</h2>

    {% for item in items %}
    <h3><a href="{% url 'home:item' item_id=item.id %}">{{item.title}}</a> Added by: {{item.user.name}} {{item.created_at}} <a href="{% url 'home:wish' wish_id=item.id %}">add to wishlist</a></h3>
    {% endfor %}
    <hr><hr>
    <a href="{% url 'home:add' %}">Add</a>
</body>
</html>

apps/home/templates/home/item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{{item.title}}</title>
    
</head>
<body>
    <p><a href="{% url 'user:logout' %}">Logout</a> <a href="{% url 'home:home' %}">Home</a></p>
    <h1>{{item.title}}</h1>
    <h2>Users who added {{item.title}} to their wish list:</h2>

    {% for wisher in wish %}
        <h3>{{wisher.wisher.name}}</h3>
    {% endfor %}
    
</body>
</html>

apps/main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <title>Login/Register</title>

</head>

        <h1>Welcome!</h1>
      
            <h2>Register</h2>
            <form action="{% url 'user:register' %}" method="POST">
                {% csrf_token %}
                Name: <input type="text" name="html_name"><br>
                Username: <input type="text" name="html_username"><br>
                Email: <input type="email" name="html_email"> <br>
                Password: <input type="password" name="html_password"> <br>
                *Password should be at least 8 characters<br>
                Confirm PW: <input type="password" name="html_confirm"><br>
                Date Hired: <input type="date" name="html_date"><br>
                            <input type="submit" value="Register">
            </form> 
            {% for m in messages %}
                <p>{{m}}</p>
            {% endfor %}
            <br>
            <br>
            <h2>Login</h2>
            <form action="{% url 'user:login' %}" method="POST">
                {% csrf_token %}
                Username: <input type="text" name="html_username"><br>
                Password: <input type="password" name="html_password"><br>
            <input type="submit" value="Login">
            </form>
    </body>
    </html>
  
        